# GRAIL

Docs: https://<USER>.github.io/GRAIL  
Dry-run: see notebooks/quickstart.ipynb or run python -m src.grail.demo --out figs_demo/
"@ | Set-Content README.md -Encoding UTF8

@"
name: grail
channels: [conda-forge]
dependencies:
  - python=3.11
  - numpy=1.26
  - scipy=1.10
  - scanpy=1.9.8
  - anndata=0.9.2
  - umap-learn=0.5.5
  - matplotlib>=3.7,<3.9
  - pip
  - pip:
      - mkdocs-material
      - mkdocs-jupyter
